### ISSUE TITLE
Scram process failing with incorrect challenge format

### ISSUE THREAD

**Issue by hasangyulyustan** [alinradut/SCRAM-Swift#1]
The scram process failing with incorrect challenge format. It happens when servernonce is containing a comma and it breaks the logic in the following line:

 let components = challenge.components(separatedBy: ",")

**Comment by alinradut** [comment]
Can you provide some sample input?

Btw, the , character is not allowed as per the SCRAM RFC: https://datatracker.ietf.org/doc/html/rfc5802#section-5.1

         The characters ',' or '=' in usernames are sent as '=2C' and
         '=3D' respectively.  If the server receives a username that
         contains '=' not followed by either '2C' or '3D', then the
         server MUST fail the authentication.

It needs to be escaped to =2C.

**Comment by hasangyulyustan** [comment]
Thank you for the fast response. Here is an example challenge string. To be honest I haven't checked if it is allowed or not but in this case it fails in guard statement in line 116.

r=v\'T8s1MQpPFTV=vC-\\\\<V,b8W~=R5R1.6hl9fbxhhoRX~UsB[r],s=I3ySIMiIKb2SCHqY7qmB7uKBd1wMQcV7iFS7pqcNzJs=,i=4096

**Comment by hasangyulyustan** [comment]
I think using regex or splitting the string by ",s=" and ",i=" could be workaround for the issue.
Usually as I see you are right. "," should be excluded :)

r: This attribute specifies a sequence of random printable ASCII
      characters excluding ',' (which forms the nonce used as input to
      the hash function). 
      
      
Anyway... Thank you for your response :)

**Comment by hasangyulyustan** [comment]
@alinradut Actually I found that the issue is caused by random nonce generation in Random struct. Based on documentation you previously mentioned comma (,) should be excluded. But the following char array in line 33 in Random.swift file contains and causes generation of wrong nonce string. :)

        var characters: [Character] = stride(from: 33, to: 127, by: 1).map({ Character(UnicodeScalar($0 as UInt8)) })

**Comment by alinradut** [comment]
Thanks for tracing this. I just pushed an update for 0.0.6 that excludes commas from the nonce generation.
